[project]
name = "05-lab"
version = "0.1.0"
description = "Taylor Series Programming Assignment"
readme = "README.md"

# developed on python v3.13
#requires-python = ">=3.13"

requires-python = ">=3.8"
dependencies = [
    #"matplotlib>=3.7.5",
    "matplotlib>=3.5.0",
]
